temporary fix on torch version
temporary fix on torch for conflict dependency with `torchtext.legacy`

```
ERROR: Cannot install -r requirements.txt (line 1) and joeynmt because these package versions have conflicting dependencies.

The conflict is caused by:
    joeynmt 1.4 depends on torch>=1.9.0
    torchtext 0.9.0 depends on torch==1.8.0
```